language: php
php:
  - 5.6
  - hhvm
  - '7' # or '7.0'


before_install:
  - mysql -e "create database IF NOT EXISTS mage1;"
  - cd work
  - pwd
  - whoami
  - cp templates.json.travis templates.json
  - composer self-update
  - composer install
  - sh ./bin/deploy/post_install.sh


script:
  - phpunit --configuration ./test/unit/phpunit.dist.xml
  - phpunit --configuration ./test/functional/phpunit.dist.xml


notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: always # [always|never|change], default: change
    on_failure: always # [always|never|change], default: change