sudo: false # use container-based environment on Travis
language: php
php:
  - 5.6
  - hhvm
  - '7'

before_install:
  - cd work # go to root folder for development environment
  - pwd # control current path ('LOCAL_ROOT' in templates.json)
  - cp templates.json.travis templates.json # create configuration for Travis from template
  - composer self-update  # update composer to prevent error Class 'Composer\Installer\PackageEvents' not found in
#   .../work/vendor/aydin-hassan/magento-core-composer-installer/src/CoreManager.php on line 109
  - composer install  # install project using PHP Composer
  - cat ./bin/deploy/post_install.sh  # control parameters in the installation script
  - cat ./bin/deploy/post_install.sql # control parameters in the SQL script
  - sh ./bin/deploy/post_install.sh # create initial DB, run SQL script, setup permissions, ...

script:
  - phpunit --configuration ./test/unit/phpunit.dist.xml  # run project's unit tests
  - phpunit --configuration ./test/functional/phpunit.dist.xml # run project's functional tests

notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: change # [always|never|change], default: change
    on_failure: change # [always|never|change], default: change